/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    authors: Author;
    articles: Article;
    categories: Category;
    tags: Tag;
    products: Product;
    media: Media;
    'article-imports-log': ArticleImportsLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'article-imports-log': ArticleImportsLogSelect<false> | ArticleImportsLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Gerado automaticamente a partir do nome se vazio.
   */
  slug: string;
  /**
   * 3-4 linhas. Aparece em /sobre e no rodape de cada artigo.
   */
  bio?: string | null;
  avatar?: (number | null) | Media;
  email?: string | null;
  social?: {
    twitter?: string | null;
    linkedin?: string | null;
    github?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Posts do blog. Adaptacao editorial (nao traducao fiel). Fonte sempre citada.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  /**
   * Resumo curto (~200 caracteres). Aparece no listing e meta description.
   */
  excerpt?: string | null;
  body_lexical: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Cover gerado automaticamente via OG dinamico (/og/[slug]) se vazio. Faca override apenas se quiser foto/AI especifica.
   */
  cover_image?: (number | null) | Media;
  /**
   * Sobrescreve o cover dinamico (uso pontual).
   */
  cover_image_override?: (number | null) | Media;
  source?: {
    original_title?: string | null;
    original_author?: string | null;
    original_site?: string | null;
    original_url?: string | null;
    original_published_at?: string | null;
    license_note?: string | null;
  };
  language_origin: 'en' | 'pt-br' | 'other';
  disclaimer_variant: 'ai-translated' | 'ai-adapted-from-text' | 'original';
  /**
   * Marca artigo com adaptacao forte. Mostra tag [Bitflix Take] no listing/article.
   */
  is_bitflix_take?: boolean | null;
  /**
   * Habilita rota /blog/[slug]/slides com reveal.js.
   */
  has_slides?: boolean | null;
  /**
   * 8-12 slides geralmente. Geradas automaticamente pela skill /blog-import.
   */
  slides_blocks?:
    | {
        slide_title?: string | null;
        slide_content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        slide_image?: (number | null) | Media;
        speaker_notes?: string | null;
        id?: string | null;
      }[]
    | null;
  author: number | Author;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  status: 'draft' | 'review' | 'published';
  /**
   * Setado automaticamente quando status muda para "published" se vazio.
   */
  published_at?: string | null;
  /**
   * Soft delete. Artigos inativos nao aparecem no site publico.
   */
  is_active?: boolean | null;
  /**
   * Auditoria. Setado pelo endpoint /api/blog-import.
   */
  created_via: 'manual' | 'blog-import-skill';
  updatedAt: string;
  createdAt: string;
}
/**
 * Taxonomia dinamica: criadas pela skill /blog-import ou manualmente. Sem categorias seed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Soft delete. Categorias inativas nao aparecem no site publico.
   */
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tags livres geradas pela skill /blog-import (5-10 por artigo).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SaaS proprios da Bitflix. Vitrine na home + grid em /produtos. CTA externo para o dominio do produto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  /**
   * Frase curta (~80 chars) que resume o produto.
   */
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Sem protocolo. Ex: meuml.com
   */
  domain: string;
  /**
   * Link externo. Se vazio, derivado de https://{domain}.
   */
  cta_url?: string | null;
  status: 'producao' | 'recem-lancado' | 'em-desenvolvimento';
  logo?: (number | null) | Media;
  /**
   * Destacar na home (se mais de 4 featured, ordenar por display_order).
   */
  featured?: boolean | null;
  /**
   * Ordem ascendente (menor primeiro).
   */
  display_order?: number | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only. Editar/apagar bloqueado. Auditoria do /api/blog-import.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-imports-log".
 */
export interface ArticleImportsLog {
  id: number;
  article: number | Article;
  source_url?: string | null;
  import_method: 'url' | 'text-paste';
  /**
   * Identificador do token usado (hash dos primeiros 8 chars).
   */
  triggered_by?: string | null;
  /**
   * Resumo curto da adaptacao feita pelo LLM (categorias sugeridas, voz, etc).
   */
  llm_summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'article-imports-log';
        value: number | ArticleImportsLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  email?: T;
  social?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        github?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body_lexical?: T;
  cover_image?: T;
  cover_image_override?: T;
  source?:
    | T
    | {
        original_title?: T;
        original_author?: T;
        original_site?: T;
        original_url?: T;
        original_published_at?: T;
        license_note?: T;
      };
  language_origin?: T;
  disclaimer_variant?: T;
  is_bitflix_take?: T;
  has_slides?: T;
  slides_blocks?:
    | T
    | {
        slide_title?: T;
        slide_content?: T;
        slide_image?: T;
        speaker_notes?: T;
        id?: T;
      };
  author?: T;
  categories?: T;
  tags?: T;
  status?: T;
  published_at?: T;
  is_active?: T;
  created_via?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  domain?: T;
  cta_url?: T;
  status?: T;
  logo?: T;
  featured?: T;
  display_order?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-imports-log_select".
 */
export interface ArticleImportsLogSelect<T extends boolean = true> {
  article?: T;
  source_url?: T;
  import_method?: T;
  triggered_by?: T;
  llm_summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configuracoes globais do site. Placeholders editaveis aqui ate receber valores definitivos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Manifesto Bitflix (~4-6 linhas). Aparece no hero da home e na intro de /sobre.
   */
  manifesto?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Formato internacional sem +: ex 5551999999999
   */
  whatsapp_number?: string | null;
  whatsapp_messages?: {
    /**
     * Mensagem padrao usada se CTA nao especificar.
     */
    default?: string | null;
    /**
     * Quando user clica em CTA dentro de card de produto SaaS.
     */
    from_saas_card?: string | null;
    /**
     * CTA do trilho custom (mid/large) em /servicos.
     */
    from_custom_cta?: string | null;
    /**
     * Footer de cada artigo do blog.
     */
    from_blog_footer?: string | null;
  };
  /**
   * Opcional. Mostrado em /contato se preenchido.
   */
  email_institutional?: string | null;
  /**
   * Criar website em https://stats.bitflix.com.br/dashboard e copiar o ID aqui. Script so injeta em producao.
   */
  umami_website_id?: string | null;
  /**
   * Anotacoes livres sobre estrategia de migracao da LP atual em bitflix.com.br. Apagavel quando cutover concluido.
   */
  migration_strategy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Menu principal e links do rodape.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  main_menu?:
    | {
        label: string;
        href: string;
        /**
         * Se true, abre em nova aba e usa rel=noopener.
         */
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footer_links?:
    | {
        label: string;
        href: string;
        /**
         * Se true, abre em nova aba e usa rel=noopener.
         */
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  manifesto?: T;
  whatsapp_number?: T;
  whatsapp_messages?:
    | T
    | {
        default?: T;
        from_saas_card?: T;
        from_custom_cta?: T;
        from_blog_footer?: T;
      };
  email_institutional?: T;
  umami_website_id?: T;
  migration_strategy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  main_menu?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  footer_links?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}